branch-defaults:
  default:
    environment: clinical-trial-final
    group_suffix: null
  master:
    environment: clinical-trial-finder
global:
  application_name: clinical-trial-final
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: python-3.6
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
